#pragma checksum "MainWindow.xaml" "{ff1816ec-aa5e-4d10-87f7-6f4963833460}" "08AF8742AB14582C8A3ABA21DBF1D9C0282E5280"
//------------------------------------------------------------------------------
// <auto-generated>
//     Ten kod został wygenerowany przez narzędzie.
//     Wersja wykonawcza:4.0.30319.42000
//
//     Zmiany w tym pliku mogą spowodować nieprawidłowe zachowanie i zostaną utracone, jeśli
//     kod zostanie ponownie wygenerowany.
// </auto-generated>
//------------------------------------------------------------------------------

using Kalkulator;
using System;
using System.Diagnostics;
using System.Windows;
using System.Windows.Automation;
using System.Windows.Controls;
using System.Windows.Controls.Primitives;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Ink;
using System.Windows.Input;
using System.Windows.Markup;
using System.Windows.Media;
using System.Windows.Media.Animation;
using System.Windows.Media.Effects;
using System.Windows.Media.Imaging;
using System.Windows.Media.Media3D;
using System.Windows.Media.TextFormatting;
using System.Windows.Navigation;
using System.Windows.Shapes;
using System.Windows.Shell;


namespace Kalkulator {
    
    
    /// <summary>
    /// MainWindow
    /// </summary>
    public partial class MainWindow : System.Windows.Window, System.Windows.Markup.IComponentConnector {
        
        
        #line 30 "MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button p7;
        
        #line default
        #line hidden
        
        
        #line 31 "MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button p8;
        
        #line default
        #line hidden
        
        
        #line 32 "MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button p9;
        
        #line default
        #line hidden
        
        
        #line 33 "MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button p4;
        
        #line default
        #line hidden
        
        
        #line 34 "MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button p5;
        
        #line default
        #line hidden
        
        
        #line 35 "MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button p6;
        
        #line default
        #line hidden
        
        
        #line 36 "MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button p1;
        
        #line default
        #line hidden
        
        
        #line 37 "MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button p2;
        
        #line default
        #line hidden
        
        
        #line 38 "MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button p3;
        
        #line default
        #line hidden
        
        
        #line 40 "MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button p0;
        
        #line default
        #line hidden
        
        
        #line 41 "MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button pcomma;
        
        #line default
        #line hidden
        
        
        #line 43 "MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button pdziel;
        
        #line default
        #line hidden
        
        
        #line 44 "MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button pmnoz;
        
        #line default
        #line hidden
        
        
        #line 45 "MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button pdodaj;
        
        #line default
        #line hidden
        
        
        #line 46 "MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button pminus;
        
        #line default
        #line hidden
        
        
        #line 47 "MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button prowna;
        
        #line default
        #line hidden
        
        
        #line 48 "MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button ppotega;
        
        #line default
        #line hidden
        
        
        #line 49 "MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button pprocent;
        
        #line default
        #line hidden
        
        
        #line 50 "MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button ppierwiastek;
        
        #line default
        #line hidden
        
        
        #line 51 "MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button pmodulo;
        
        #line default
        #line hidden
        
        
        #line 52 "MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button pbin;
        
        #line default
        #line hidden
        
        
        #line 53 "MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button psil;
        
        #line default
        #line hidden
        
        
        #line 56 "MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button pC;
        
        #line default
        #line hidden
        
        
        #line 59 "MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button pznak;
        
        #line default
        #line hidden
        
        
        #line 62 "MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox txtwyswietlacz;
        
        #line default
        #line hidden
        
        
        #line 64 "MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label pamiec;
        
        #line default
        #line hidden
        
        private bool _contentLoaded;
        
        /// <summary>
        /// InitializeComponent
        /// </summary>
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0")]
        public void InitializeComponent() {
            if (_contentLoaded) {
                return;
            }
            _contentLoaded = true;
            System.Uri resourceLocater = new System.Uri("/Kalkulator;component/mainwindow.xaml", System.UriKind.Relative);
            
            #line 1 "MainWindow.xaml"
            System.Windows.Application.LoadComponent(this, resourceLocater);
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0")]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily")]
        void System.Windows.Markup.IComponentConnector.Connect(int connectionId, object target) {
            switch (connectionId)
            {
            case 1:
            this.p7 = ((System.Windows.Controls.Button)(target));
            
            #line 30 "MainWindow.xaml"
            this.p7.Click += new System.Windows.RoutedEventHandler(this.p_Click);
            
            #line default
            #line hidden
            return;
            case 2:
            this.p8 = ((System.Windows.Controls.Button)(target));
            
            #line 31 "MainWindow.xaml"
            this.p8.Click += new System.Windows.RoutedEventHandler(this.p_Click);
            
            #line default
            #line hidden
            return;
            case 3:
            this.p9 = ((System.Windows.Controls.Button)(target));
            
            #line 32 "MainWindow.xaml"
            this.p9.Click += new System.Windows.RoutedEventHandler(this.p_Click);
            
            #line default
            #line hidden
            return;
            case 4:
            this.p4 = ((System.Windows.Controls.Button)(target));
            
            #line 33 "MainWindow.xaml"
            this.p4.Click += new System.Windows.RoutedEventHandler(this.p_Click);
            
            #line default
            #line hidden
            return;
            case 5:
            this.p5 = ((System.Windows.Controls.Button)(target));
            
            #line 34 "MainWindow.xaml"
            this.p5.Click += new System.Windows.RoutedEventHandler(this.p_Click);
            
            #line default
            #line hidden
            return;
            case 6:
            this.p6 = ((System.Windows.Controls.Button)(target));
            
            #line 35 "MainWindow.xaml"
            this.p6.Click += new System.Windows.RoutedEventHandler(this.p_Click);
            
            #line default
            #line hidden
            return;
            case 7:
            this.p1 = ((System.Windows.Controls.Button)(target));
            
            #line 36 "MainWindow.xaml"
            this.p1.Click += new System.Windows.RoutedEventHandler(this.p_Click);
            
            #line default
            #line hidden
            return;
            case 8:
            this.p2 = ((System.Windows.Controls.Button)(target));
            
            #line 37 "MainWindow.xaml"
            this.p2.Click += new System.Windows.RoutedEventHandler(this.p_Click);
            
            #line default
            #line hidden
            return;
            case 9:
            this.p3 = ((System.Windows.Controls.Button)(target));
            
            #line 38 "MainWindow.xaml"
            this.p3.Click += new System.Windows.RoutedEventHandler(this.p_Click);
            
            #line default
            #line hidden
            return;
            case 10:
            this.p0 = ((System.Windows.Controls.Button)(target));
            
            #line 40 "MainWindow.xaml"
            this.p0.Click += new System.Windows.RoutedEventHandler(this.p_Click);
            
            #line default
            #line hidden
            return;
            case 11:
            this.pcomma = ((System.Windows.Controls.Button)(target));
            
            #line 41 "MainWindow.xaml"
            this.pcomma.Click += new System.Windows.RoutedEventHandler(this.p_Click);
            
            #line default
            #line hidden
            return;
            case 12:
            this.pdziel = ((System.Windows.Controls.Button)(target));
            
            #line 43 "MainWindow.xaml"
            this.pdziel.Click += new System.Windows.RoutedEventHandler(this.Op_Click);
            
            #line default
            #line hidden
            return;
            case 13:
            this.pmnoz = ((System.Windows.Controls.Button)(target));
            
            #line 44 "MainWindow.xaml"
            this.pmnoz.Click += new System.Windows.RoutedEventHandler(this.Op_Click);
            
            #line default
            #line hidden
            return;
            case 14:
            this.pdodaj = ((System.Windows.Controls.Button)(target));
            
            #line 45 "MainWindow.xaml"
            this.pdodaj.Click += new System.Windows.RoutedEventHandler(this.Op_Click);
            
            #line default
            #line hidden
            return;
            case 15:
            this.pminus = ((System.Windows.Controls.Button)(target));
            
            #line 46 "MainWindow.xaml"
            this.pminus.Click += new System.Windows.RoutedEventHandler(this.Op_Click);
            
            #line default
            #line hidden
            return;
            case 16:
            this.prowna = ((System.Windows.Controls.Button)(target));
            
            #line 47 "MainWindow.xaml"
            this.prowna.Click += new System.Windows.RoutedEventHandler(this.prowna_Click);
            
            #line default
            #line hidden
            return;
            case 17:
            this.ppotega = ((System.Windows.Controls.Button)(target));
            
            #line 48 "MainWindow.xaml"
            this.ppotega.Click += new System.Windows.RoutedEventHandler(this.Op_Click);
            
            #line default
            #line hidden
            return;
            case 18:
            this.pprocent = ((System.Windows.Controls.Button)(target));
            
            #line 49 "MainWindow.xaml"
            this.pprocent.Click += new System.Windows.RoutedEventHandler(this.Op_Click);
            
            #line default
            #line hidden
            return;
            case 19:
            this.ppierwiastek = ((System.Windows.Controls.Button)(target));
            
            #line 50 "MainWindow.xaml"
            this.ppierwiastek.Click += new System.Windows.RoutedEventHandler(this.Op_Click);
            
            #line default
            #line hidden
            return;
            case 20:
            this.pmodulo = ((System.Windows.Controls.Button)(target));
            
            #line 51 "MainWindow.xaml"
            this.pmodulo.Click += new System.Windows.RoutedEventHandler(this.Op_Click);
            
            #line default
            #line hidden
            return;
            case 21:
            this.pbin = ((System.Windows.Controls.Button)(target));
            
            #line 52 "MainWindow.xaml"
            this.pbin.Click += new System.Windows.RoutedEventHandler(this.Op_Click);
            
            #line default
            #line hidden
            return;
            case 22:
            this.psil = ((System.Windows.Controls.Button)(target));
            
            #line 53 "MainWindow.xaml"
            this.psil.Click += new System.Windows.RoutedEventHandler(this.Op_Click);
            
            #line default
            #line hidden
            return;
            case 23:
            this.pC = ((System.Windows.Controls.Button)(target));
            
            #line 56 "MainWindow.xaml"
            this.pC.Click += new System.Windows.RoutedEventHandler(this.pC_Click);
            
            #line default
            #line hidden
            return;
            case 24:
            this.pznak = ((System.Windows.Controls.Button)(target));
            
            #line 59 "MainWindow.xaml"
            this.pznak.Click += new System.Windows.RoutedEventHandler(this.pznak_Click);
            
            #line default
            #line hidden
            return;
            case 25:
            this.txtwyswietlacz = ((System.Windows.Controls.TextBox)(target));
            return;
            case 26:
            this.pamiec = ((System.Windows.Controls.Label)(target));
            return;
            }
            this._contentLoaded = true;
        }
    }
}

